### ISSUE TITLE
Add template enemy

### ISSUE THREAD

**Issue by StephenHapp** [gmuGADIG/Princess-Starshine#21]
DoD: Prefab created that serves as the base for all enemy types to be made from. Enemy prefab takes of physical space in the level. Enemy prefab takes damage and plays SFX when hit by player's weapons. Enemy prefab displays a sprite. Moves towards player. Includes public variables for design team to tweak the amount of health, amount of XP dropped, movement speed.

**Comment by ServerDaLite** [comment]
The code and prefab is in SubTeam2
