### ISSUE TITLE
Tell The Player They Can Skip Cutscenes

### ISSUE THREAD

**Issue by Aegistus** [gmuGADIG/Princess-Starshine#286]

**Comment by Justin1L8** [comment]
This functionality already exists (press tilde during a cutscene); the issue is communicating it to the player, so I'm gonna change the issue to be about that

**Comment by Justin1L8** [comment]
I suggest changing the key to escape (can't remember why I didn't do that when it was implemented. maybe I thought it'd conflict with something?) and showing some text to say it can be skipped. Ideally the text would only appear when the player presses a few buttons, but a lower-effort solution is just keeping the text on-screen.

**Comment by micycle8778** [comment]
Binding skip to escape conflicts with the pause menu
