### ISSUE TITLE
Block Out Main Menu

### ISSUE THREAD

**Issue by Aegistus** [gmuGADIG/Princess-Starshine#44]
DoD: The main menu should have the following elements:
-Title
-New Run button
-Continue button
-Options button
-Quit button

Note: These elements do not have to be functional or pretty. That will be worked on later.

**Comment by StephenHapp** [comment]
Is this covered already by #16 ?

**Comment by MistOfJudgement** [comment]
View is affected by screen size (window aspect ratio)
