### ISSUE TITLE
Add DoDs to the weapons tasks

### ISSUE THREAD

**Issue by StephenHapp** [gmuGADIG/Princess-Starshine#64]
DoD: Each weapon task (#52 - #63) has a DoD matching the design document's description of the weapon.

Do Stephen a big favor and write these out (pretty please)

**Comment by SunMoon97** [comment]
Hello,

I'm new to the feild of open source contribution and would appreciate some guidance on how to approach this following issue:
I haven't started working on this issue yet, and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!

Best regards,
